name: l2dVE
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - pytorch
  - torchvision
  - pip
  - pip:
    - numpy
    - matplotlib
    - notebook
    - jupyter
    - ipykernel # required for jupyter notebook in VS Code
    - scikit-learn
    - medmnist
    - seaborn
